# Generated by Django 2.1.15 on 2022-12-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField(default=0)),
                ('available_seats', models.IntegerField(default=60)),
                ('weekly', models.BooleanField(default=False)),
                ('dialy', models.BooleanField(default=True)),
                ('time', models.TimeField()),
            ],
        ),
    ]
