# Generated by Django 2.1.15 on 2022-12-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.IntegerField(default=0)),
                ('flight_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='flights',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flights',
            name='fromAdr',
            field=models.CharField(default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='flights',
            name='toAdr',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
