# Generated by Django 2.1.15 on 2022-12-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_auto_20221229_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('tickets_available', models.IntegerField(default=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='flights',
            name='weekly',
        ),
        migrations.AddField(
            model_name='flights',
            name='Week_day',
            field=models.CharField(default='', max_length=10),
        ),
    ]
