# Generated by Django 2.1.15 on 2022-12-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_auto_20221230_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flights',
            name='Week_day',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
