# Generated by Django 2.1.15 on 2022-12-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_auto_20221230_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='customer_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='bookings',
            name='number',
            field=models.IntegerField(default=60),
        ),
    ]
