# Generated by Django 2.1.15 on 2022-12-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSeats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('number_of_available', models.IntegerField(default=60)),
                ('flight_number', models.IntegerField(default=0)),
                ('flight_name', models.CharField(max_length=100)),
            ],
        ),
    ]
